config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :users, except: [:index] do
    resources :favorites, except: [:edit, :update]
  end

  resources :hospitals
  resources :sessions, only: [:create]

  get '/search/hospitals' => 'hospitals#search'

  get 'signup' => 'users#new'
  get '/signin' => 'sessions#new'
  delete 'signout' => 'sessions#destroy'

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :hospital


end

app/models/hospital.rb
class Hospital < ActiveRecord::Base
  has_many :favorites, dependent: :destroy
  has_many :users, through: :favorites


end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :favorites, dependent: :destroy
  has_many :hospitals, through: :favorites

  # Add handlers to run when creating and saving
  before_create :create_remember_token
  before_save :normalize_fields

  # Validate name:
  validates :first_name,
    presence: true,
    length: { maximum: 50 }

  validates :last_name,
    presence: true,
    length: { maximum: 50 }

  # Validate email address:
  validates :email,
    presence: true,
    uniqueness: { case_sensitive: false },
    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }


  # Secure password features:
  has_secure_password

  # Create a new remember token for a user:
  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  # Hash a token:
  def User.hash(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

  # Creates a new session token for the user:
  def create_remember_token
    self.remember_token = User.hash(User.new_remember_token)
  end

  # Normalize fields for consistency:
  def normalize_fields
    self.email.downcase!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :load_favorite, only: [:show, :edit, :update, :destroy]


  def index
    @user = User.find(current_user)
    @favorites = @user.favorites
  end

  def new
    @favorite = Favorite.new
  end

  def create
    @hospital = Hospital.new(hospital_params)
    @hospital.address = params[:data][:address]
    @hospital.zip_code = params[:data][:zip_code]
    @hospital.phone = params[:data][:phone_number][:phone_number]
    @hospital.save
    @favorite = Favorite.new
    @favorite.user_id = current_user.id
    @favorite.hospital_id = @hospital.id
    @favorite.save
    redirect_to user_favorites_path(current_user)
  end

  def destroy
    @favorite.destroy
    redirect_to user_favorites_path(current_user)
  end

  private

  def hospital_params
    params.require(:data).permit(:id, :hospital_name, :address, :city, :state, :zip_code, :phone, :score, :measure)
  end

  # def favorite_params
  #   params.require(:data).permit(:id, :hospital_id, :user_id)
  # end

  def load_favorite
    return @favorite = Favorite.find(params[:id])
  end
end

app/controllers/hospitals_controller.rb
class HospitalsController < ApplicationController

  def index
    @procedures = []
    temp_procedures = HTTParty.get("http://data.medicare.gov/resource/77hc-ibv8.json?$select=measure_name")
    temp_procedures.each do |procedure|
      # binding.pry
      @procedures.push(procedure["measure_name"])
    end
    @procedures.uniq!
  end

  def search
    @state = params[:state]
    @procedure = params[:procedure]
    @hospitals = get_results(@state, @procedure)
  end

  private

  def get_results(state, procedure)
      procedure = procedure.gsub(" ", "%20")
      temp_results = HTTParty.get("http://data.medicare.gov/resource/77hc-ibv8.json?state=#{state}&measure_name=#{procedure}")
      temp_results.delete_if {|result| result["score"] == "Not Available" || result["score"] == "-"}
      results = temp_results.sort_by do |result|
        result["score"].to_f
      end
      return results
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    # Find the user by email:
    user = User.find_by(email: params[:session][:email].downcase)

    # Test if the user was found AND authenticates
    if user && user.authenticate(params[:session][:password])
      sign_in(user)
      redirect_back_or root_url
    else
      flash[:error] = 'Invalid email/password'
      redirect_to signin_path
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_signin, except: [:new, :create]
  before_action :find_user, only: [:show, :edit, :update, :destroy]
  before_action :require_current_user, except: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in(@user)
      redirect_to @user
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to root_path
  end

  private

  def find_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(
      :first_name,
      :last_name,
      :email,
      :password,
      :password_confirmation
    )
  end

  def require_current_user
    if !current_user?(@user)
      redirect_to root_path
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index

  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Current User methods:

  def current_user
    remember_token = User.hash(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user?(user)
    current_user == user
  end

  # Signin Status methods:

  def signed_in?
    !current_user.nil?
  end

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.hash(remember_token))
    self.current_user = user
  end

  def sign_out
    current_user.update_attribute(:remember_token, User.hash(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  # Location Management methods:

  def store_location
    if request.get?
      session[:return_to] = request.url
    end
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  # Security Checkpoint method:

  def require_signin
    unless signed_in?
      store_location
      flash[:error] = 'Please sign in.'
      redirect_to signin_url
    end
  end
end

app/views/common/_common.html.erb
<% if signed_in? %>
  <nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" >Hospital-truthed</a>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Search", hospitals_path %></li>
          <li><%= link_to "My Favorites", user_favorites_path(current_user) %></li>
          <li><a href="http://www.cdc.gov/hai/">HAI</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <%= form_for :session, url: signout_path, method: 'delete' do |f| %>
            Signed in as <%= link_to current_user.first_name, current_user %>
            </br>
            <%= f.submit "Sign out", id: 'signout' %>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>


  <% else %>
  <nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand">Hospital-truthed</a>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><%= link_to "Home", root_path %></li>
          <li><a href="http://www.cdc.gov/hai/">HAI</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Sign In", signin_path %></li>
          <li><%= link_to "Sign up", signup_path %></li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>


<% end %>

app/views/favorites/index.html.erb
<h2>Favorited Hospitals</h2>

<table id="favorited-hospitals" class="table table-hover">
    <thead>
      <tr>
        <th>Name</th>
        <th>Address</th>
        <th>City</th>
        <th>State</th>
        <th>Phone Number</th>
      </tr>
    </thead>
    <% @favorites.each do |favorite| %>
    <tbody>
      <tr>
        <th><%= favorite.hospital.hospital_name %> </th>
        <th><%= favorite.hospital.address %></th>
        <th><%= favorite.hospital.city %></th>
        <th><%= favorite.hospital.state %></th>
        <th><%= favorite.hospital.phone %></th>
        <td><%= button_to "Delete" , user_favorite_path(current_user, favorite.id), method: "delete" %></td>
      </tr>
    </tbody>
    <% end %>

app/views/hospitals/_form.html.erb
<div id="search-container">
  <%= form_tag( search_hospitals_path, method: "get") do |f| %>
  <%= label_tag("State:") %>
  <%= select_tag :state, options_for_select(["AL","AK", "AZ", "AR", "CA", "CO","CT", "DC", "DE", "FL", "GA", "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY"]) %>
  <%= label_tag("Procedure:") %>
  <%= select_tag(:procedure, options_for_select(@procedures)) %>
  <%= submit_tag("Search") %>
  <% end %>
</div>

app/views/hospitals/index.html.erb
<h2>Search</h2>

<% if signed_in? %>
  <%= render "form" %>
<% end %>

app/views/hospitals/search.html.erb
<h2>Results for <%= params[:procedure] %></h2>


  <table id="hospitals" class="table table-hover">
    <thead>
      <tr>
        <th>Name</th>
        <th>City</th>
        <th>State</th>
        <th>Score</th>
      </tr>
    </thead>
    <% @hospitals.each do |hospital| %>
    <tbody>
      <tr>
        <th><%= hospital["hospital_name"] %> </th>
        <th><%= hospital["city"] %></th>
        <th><%= hospital["state"] %></th>
        <th><%= hospital["score"] %></th>
        <td><%= button_to "Favorite", action: "create", controller: "favorites", user_id: current_user, data: hospital%></td>
      </tr>
    </tbody>
    <% end %>


  </table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="/assets/bootstrap.css?body=1" media="screen" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <title>Hospital-truthed</title>

  </head>
  <body>
    <%= render 'common/common' %>
    <%= yield %>


    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="js/bootstrap.min.js"></script>
  </body>
</html>

app/views/users/_user_form.html.erb
<% if @user.errors.any? %>
<b>Errors:</b>
<ul>
  <% @user.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
  <% end %>
</ul>
<% end %>

<%= form_for @user do |f| %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>

  <%= f.label :last_name %>
  <%= f.text_field :last_name %>

  <%= f.label :email %>
  <%= f.text_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation, 'Confirm Password' %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "Submit", id: 'submit' %>
<% end %>

app/views/users/edit.html.erb
<h1>Edit "<%= @user.first_name %> <%= @user.last_name %>"</h1>
<%= render "user_form" %>

<hr>

<%= form_for @user, method: 'delete' do |f| %>
  <%= f.submit "Delete" %>
<% end %>

<hr>

<%= link_to "Cancel", @user %>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= render "user_form" %>

app/views/users/show.html.erb
<h1><%= @user.first_name %> <%= @user.last_name %></h1>

<p><%= @user.email %></p>

<p><%= link_to "Edit", edit_user_path(@user) %></p>

app/views/welcome/index.html.erb
<div id="welcome-container">
  <div class="welcome">
    <h1>Hospitalized? Hospital-truthed</h1>

    <h2><i>Find the safest care for your procedure</i></h2>
  </div>
</div>